networks:
  default:
    external: true
    name: qgis_devtools_postgis_net

services:
  r-studio:
    build:
      context: .
      dockerfile: Dockerfile.rstudio
    ports:
      - 8787:8787
    volumes:
      - ./src:/home/rstudio/src
    environment:
      - PASSWORD=yourpassword
    container_name: r-studio
    
  niche-modelling:
    build:
      context: .
      dockerfile: Dockerfile.python
    container_name: niche-modelling
    image: niche-modelling
    volumes:
      - ${PWD}:/workdir
    networks:
      - default
    ports:
      - "8888:8888"
    command: bash -c "cd /workdir && jupyter notebook --ip=0.0.0.0 --port=8888 --no-browser --allow-root --NotebookApp.token=''"

