FROM rocker/geospatial:latest as builder

RUN apt-get update && apt-get install -y \
    libudunits2-dev \
    libgdal-dev \
    libproj-dev

RUN R -e "install.packages(c('biomod2', 'dismo', 'ggplot', 'ggmap', 'sf'), dependencies = TRUE)"

FROM rocker/rstudio:4.4.0

# Copiar las librerías de R instaladas en la etapa de construcción
COPY --from=builder /usr/local/lib/R/site-library /usr/local/lib/R/site-library

RUN apt-get update && apt-get install -y \
    libudunits2-dev \
    libgdal-dev \
    libproj-dev

# Exponer el puerto 8787 para RStudio
EXPOSE 8787

# Iniciar RStudio
CMD ["/init"]