networks:
  default:
    external: true
    name: qgis_devtools_postgis_net

services:
  r-studio:
    build:
      context: .
      dockerfile: Dockerfile.rstudio
    ports:
      - "8787:8787"
    volumes:
      - ${PWD}:/workdir
    environment:
      - USER=rstudio
      - PASSWORD=yourpassword
    container_name: r-studio

  wallace:
    build:
      context: .
      dockerfile: Dockerfile.wallace
    ports:
      - "3333:3838"
    volumes:
      - ${PWD}:/workdir
    container_name: wallace
    
    
  niche-modelling:
    build:
      context: .
      dockerfile: Dockerfile.python
    container_name: niche-modelling
    image: niche-modelling
    volumes:
      - ${PWD}:/workdir
    networks:
      - default
    ports:
      - "8686:8686"
    command: bash -c "cd /workdir && jupyter notebook --ip=0.0.0.0 --port=8888 --no-browser --allow-root --NotebookApp.token=''"

